/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package igu;

/**
 *
 * @author danny
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        BtnIguEjer18 = new javax.swing.JButton();
        BtnIguEjer19 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        BtnIguEjer7 = new javax.swing.JButton();
        BtnIguEjer10 = new javax.swing.JButton();
        BtnIguEjer22 = new javax.swing.JButton();
        BtnIguEjer23 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menú");

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel2.setText("Parte 1");

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel3.setText("Capítulo 3");

        BtnIguEjer18.setText("Ejercicio 18");
        BtnIguEjer18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnIguEjer18ActionPerformed(evt);
            }
        });

        BtnIguEjer19.setText("Ejercicio 19");
        BtnIguEjer19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnIguEjer19ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel4.setText("Capítulo 4");

        BtnIguEjer7.setText("Ejercicio 7");
        BtnIguEjer7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnIguEjer7ActionPerformed(evt);
            }
        });

        BtnIguEjer10.setText("Ejercicio 10");
        BtnIguEjer10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnIguEjer10ActionPerformed(evt);
            }
        });

        BtnIguEjer22.setText("Ejercicio 22");
        BtnIguEjer22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnIguEjer22ActionPerformed(evt);
            }
        });

        BtnIguEjer23.setText("Ejercicio 23");
        BtnIguEjer23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnIguEjer23ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Menú");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(BtnIguEjer7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BtnIguEjer10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BtnIguEjer22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BtnIguEjer23))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(BtnIguEjer19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BtnIguEjer18))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(24, 24, 24)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnIguEjer18, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnIguEjer19)
                .addGap(32, 32, 32)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnIguEjer7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnIguEjer10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnIguEjer22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnIguEjer23)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnIguEjer18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnIguEjer18ActionPerformed
        //Crear pantalla Ejer18
        Ejer18 pantallaEjer18 = new Ejer18();
        //Visualizar pantalla Ejer18
        pantallaEjer18.setVisible(true);
        pantallaEjer18.setLocationRelativeTo(null);
        //Ocultar pantalla menú
        setVisible(false);
    }//GEN-LAST:event_BtnIguEjer18ActionPerformed

    private void BtnIguEjer19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnIguEjer19ActionPerformed
        //Crear pantalla Ejer19
        Ejer19 pantallaEjer19 = new Ejer19();
        //Visualizar pantalla Ejer19
        pantallaEjer19.setVisible(true);
        pantallaEjer19.setLocationRelativeTo(null);
        //Ocultar pantalla menú
        setVisible(false);
    }//GEN-LAST:event_BtnIguEjer19ActionPerformed

    private void BtnIguEjer7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnIguEjer7ActionPerformed
        Ejer7 pantallaEjer7 = new Ejer7();
        pantallaEjer7.setVisible(true);
        pantallaEjer7.setLocationRelativeTo(null);
        setVisible(false);
    }//GEN-LAST:event_BtnIguEjer7ActionPerformed

    private void BtnIguEjer10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnIguEjer10ActionPerformed
        Ejer10 pantallaEjer10 = new Ejer10();
        pantallaEjer10.setVisible(true);
        pantallaEjer10.setLocationRelativeTo(null);
        setVisible(false);
    }//GEN-LAST:event_BtnIguEjer10ActionPerformed

    private void BtnIguEjer22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnIguEjer22ActionPerformed
        Ejer22 pantallaEjer22 = new Ejer22();
        pantallaEjer22.setVisible(true);
        pantallaEjer22.setLocationRelativeTo(null);
        setVisible(false);
    }//GEN-LAST:event_BtnIguEjer22ActionPerformed

    private void BtnIguEjer23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnIguEjer23ActionPerformed
        Ejer23 pantallaEjer23 = new Ejer23();
        pantallaEjer23.setVisible(true);
        pantallaEjer23.setLocationRelativeTo(null);
        setVisible(false);
    }//GEN-LAST:event_BtnIguEjer23ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnIguEjer10;
    private javax.swing.JButton BtnIguEjer18;
    private javax.swing.JButton BtnIguEjer19;
    private javax.swing.JButton BtnIguEjer22;
    private javax.swing.JButton BtnIguEjer23;
    private javax.swing.JButton BtnIguEjer7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
